### PR TITLE
Add file with LGDO-serialized histograms

### PR DESCRIPTION
**Pull request by ManuelHu**
Created with legend-pydataobj w/ https://github.com/legend-exp/legend-pydataobj/pull/98 applied

the lh5 file contain two histograms, one with binning defined via a range object, and one with a variable binning (the latter is not mentioned yet in the lh5 spec!)

the data is just a randomly generated 2d gaussian.

### CODE REVIEW

**Comment by oschulz** [comment]
@apmypb can you test this file in Julia with LegendHDF5IO?

**Comment by ManuelHu** [comment]
I added a third test histogram, now also containing units on the axes.

**Comment by oschulz** [comment]
> I added a third test histogram, now also containing units on the axes.

Thanks, I'll try to get this tested with Julia soon.

**Comment by apmypb** [comment]
Variable binning works too. Using units however does not work yet, because one can not fit a histogram with units (see https://github.com/JuliaStats/StatsBase.jl/issues/857).
Just to make sure. Is this the histogram in "test_histogram_variable":
image

**Comment by oschulz** [comment]
@ManuelHu ?

**Comment by ManuelHu** [comment]
looks good. here are (both histograms) plotted from python:

image


> Using units however does not work yet, because one can not fit a histogram with units

Also no python histogram library (that I know of) supports units on axes. So from the python side, this is also a purely informational attribute.
Do I understand it correctly, that you cannot read the histogram with units (which would be very bad), or are just the units missing in the end (which would be the same as with python)?

**Comment by apmypb** [comment]
Exactly like that. The units are just dropped during read in. The actual values of the arrays or ranges are read in correctly and can be displayed accordingly.

**Comment by oschulz** [comment]
Then I suggest we merge this - @apmypb can you then add reading these histograms to the LegendHDF5IO.jl tests?

**Comment by ManuelHu** [comment]
I just renamed `test_histogram_variable_w_attrs` to `test_histogram_range_w_attrs` (there never was a variable histogram with units in the file). After this, this PR is now ready from my side.

I will also add the tests to my legend-pydataobj pull request.

**Comment by ManuelHu** [comment]
@oschulz can we get this merged?

**Comment by oschulz** [comment]
I'll take a final look myself today, then I'll merge it. Sorry for the delay.

**Comment by oschulz** [comment]
Thanks again @ManuelHu and sorry for the delay!

**Pull request merged**
